-- This SQL script defines the database schema for a flight booking system that integrates with Duffel's API.
-- It includes tables for users, bookings, passengers, transactions, and webhook logs.

-- 1. USER TABLE
-- Tracks account holders. 
CREATE TABLE user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone_number VARCHAR(50), 
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 2. BOOKING TABLE
-- The core record linking your local system to Duffel's reality.
CREATE TABLE booking (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    pnr VARCHAR(50) UNIQUE, -- Generated by the airline, often null until ticketed
    duffel_offer_id VARCHAR(255) NOT NULL, -- The flight they selected
    duffel_order_id VARCHAR(255) UNIQUE,   -- The actual purchased ticket (Null until payment clears)
    total_price DECIMAL(10, 2) NOT NULL,   -- The Duffel total amount (Includes your markup)
    currency VARCHAR(10) NOT NULL,         -- The Duffel total currency
    status ENUM('pending', 'confirmed', 'cancelled', 'failed', 'refunded') DEFAULT 'pending',
    flight_snapshot JSON NOT NULL,         -- The raw, unparsed Duffel Offer payload
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);

CREATE INDEX idx_duffel_order ON booking(duffel_order_id);
CREATE INDEX idx_pnr ON booking(pnr);

-- 3. PASSENGER TABLE
-- Maps the strict identity requirements needed to generate a Duffel Order.
CREATE TABLE passenger (
    id INT PRIMARY KEY AUTO_INCREMENT,
    booking_id INT NOT NULL,
    duffel_passenger_id VARCHAR(255), -- Duffel's internal ID for this specific passenger
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender ENUM('m', 'f') NOT NULL,
    passport_number VARCHAR(100), 
    passenger_type ENUM('adult', 'child', 'infant_without_seat') NOT NULL,
    ticket_number VARCHAR(100) UNIQUE, -- The e-ticket number returned after a successful Order
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (booking_id) REFERENCES booking(id) ON DELETE CASCADE
);

-- 4. TRANSACTION TABLE
-- Isolates financial flow from the booking state.
CREATE TABLE transaction (
    id INT PRIMARY KEY AUTO_INCREMENT,
    booking_id INT NOT NULL,
    payment_gateway_id VARCHAR(255), -- ID from your payment processor (e.g., Stripe/Tap)
    amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    transaction_type ENUM('charge', 'refund') NOT NULL,
    status ENUM('pending', 'success', 'failed') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (booking_id) REFERENCES booking(id) ON DELETE CASCADE
);

-- 5. WEBHOOK LOG TABLE
-- The safety net for asynchronous airline updates.
CREATE TABLE webhook_log (
    id INT PRIMARY KEY AUTO_INCREMENT,
    event_type VARCHAR(100) NOT NULL,      -- e.g., 'order.created', 'order.cancelled'
    duffel_event_id VARCHAR(255) UNIQUE NOT NULL,
    payload JSON NOT NULL,                 -- The complete incoming webhook body
    processed BOOLEAN DEFAULT FALSE,       -- Flag to track if your backend handled it
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);